### ISSUE TITLE
Migrate DNS thumbor.org to CNAME 

### ISSUE THREAD

**Issue by RaphaelVRossi** [thumbor/thumbor-org#1]
We created github pages for thumbor-org at `thumbor.github.io/thumbor-org`.

Now we need to change DNS thumbor.org from ip to CNAME pointing to `thumbor.github.io/thumbor-org`.

@heynemann Do you know how can we change this DNS registry to CNAME?

**Comment by RaphaelVRossi** [comment]
@heynemann ping

**Comment by heynemann** [comment]
Can't add the name here. CNAME can only point to subdomain. Done that.

**Comment by heynemann** [comment]
Also registered thumbor.org as a domain for thumbor org.

**Comment by heynemann** [comment]
It's working as expected with HTTPS
