### ISSUE TITLE
New testimonial for my company

### ISSUE THREAD

**Issue by gabriel-kaam** [thumbor/thumbor-org#2]
### Name

Gabriel Kaam

### Email

gabriel@modalova.com

### Company name

MODALOVA

### Company website

https://modalova.com/

### Testimonial

Modalova is an online shopping website dedicated to fashion for men and women.

We use Thumbor to generate product thumbnails on our website Modalova, on the grid and also on the Product Pages.

We serve more than 2,000,000 products to our customers everyday and work with more than 10,000 brands on the fashion Market.

Our Thumbor instances are running on Heroku, behind the CDN Cloudflare.

Thanks again for this wonderful project,

Cheers!

Gabriel Kaam - CEO & Founder

**Comment by RaphaelVRossi** [comment]
Hey @gabriel-kaam, thank you for using Thumbor :blue_heart: 

Your testimonial is available! see: https://www.thumbor.org/testimonials/

![image](https://github.com/user-attachments/assets/ffa6c750-36f7-4490-89e8-046766e5cef1)
